services:


  postgres:  # Database for users, projects, etc
    image: postgres:latest
    ports:
       - "5432:5432"
    environment:
        POSTGRES_DB: "learnblocksdb"
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "password"
    volumes:
       - learnblox_postgres_data:/data/db


  minio:
    image: minio/minio:latest
    command: server /mnt/data --console-address :9091
    ports:
        - "9090:9090"
        - "9091:9091"
    environment:
        MINIO_ROOT_USER: "admin"
        MINIO_ROOT_PASSWORD: "AdminSecret"
        MINIO_VOLUMES: "/data"
    volumes:
        - learnblox_minio_data:/mnt/data

volumes:
  learnblox_minio_data:
  learnblox_postgres_data:
